// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcdt9HQQDZmIC7JHrIk3_0Rq7YBsH7wVk',
    appId: '1:335715106254:web:c980591663453790167f9f',
    messagingSenderId: '335715106254',
    projectId: 'modul12-26a1a',
    authDomain: 'modul12-26a1a.firebaseapp.com',
    storageBucket: 'modul12-26a1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGPI3vnxMLiDUrmFsfjj8nYFjy_Ap2ggA',
    appId: '1:335715106254:android:a49bcf65357abe8e167f9f',
    messagingSenderId: '335715106254',
    projectId: 'modul12-26a1a',
    storageBucket: 'modul12-26a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Xkm567ZlIi0S7WA2LChtsLADtMhEVp4',
    appId: '1:335715106254:ios:a864805a85add7f2167f9f',
    messagingSenderId: '335715106254',
    projectId: 'modul12-26a1a',
    storageBucket: 'modul12-26a1a.firebasestorage.app',
    iosBundleId: 'com.example.tpmod12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Xkm567ZlIi0S7WA2LChtsLADtMhEVp4',
    appId: '1:335715106254:ios:a864805a85add7f2167f9f',
    messagingSenderId: '335715106254',
    projectId: 'modul12-26a1a',
    storageBucket: 'modul12-26a1a.firebasestorage.app',
    iosBundleId: 'com.example.tpmod12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcdt9HQQDZmIC7JHrIk3_0Rq7YBsH7wVk',
    appId: '1:335715106254:web:84bac3104fd8a4c6167f9f',
    messagingSenderId: '335715106254',
    projectId: 'modul12-26a1a',
    authDomain: 'modul12-26a1a.firebaseapp.com',
    storageBucket: 'modul12-26a1a.firebasestorage.app',
  );

}