// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9wEG3MeKt4xgdcIppaQm2caTZzFv801E',
    appId: '1:711860102224:web:65d9545f0267232ea05d55',
    messagingSenderId: '711860102224',
    projectId: 'modul-12-e205f',
    authDomain: 'modul-12-e205f.firebaseapp.com',
    storageBucket: 'modul-12-e205f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCO8d5NSdeIhvcFCXw_gFOh5Hm0ciOQW8',
    appId: '1:711860102224:android:1469cd501e04a234a05d55',
    messagingSenderId: '711860102224',
    projectId: 'modul-12-e205f',
    storageBucket: 'modul-12-e205f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoMH440WEoHJmNoWFF-vF2ywOh00_lFpo',
    appId: '1:711860102224:ios:fb23f707d635ff33a05d55',
    messagingSenderId: '711860102224',
    projectId: 'modul-12-e205f',
    storageBucket: 'modul-12-e205f.firebasestorage.app',
    iosBundleId: 'com.example.tpmod12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoMH440WEoHJmNoWFF-vF2ywOh00_lFpo',
    appId: '1:711860102224:ios:fb23f707d635ff33a05d55',
    messagingSenderId: '711860102224',
    projectId: 'modul-12-e205f',
    storageBucket: 'modul-12-e205f.firebasestorage.app',
    iosBundleId: 'com.example.tpmod12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9wEG3MeKt4xgdcIppaQm2caTZzFv801E',
    appId: '1:711860102224:web:79f8e5f43b7d00ffa05d55',
    messagingSenderId: '711860102224',
    projectId: 'modul-12-e205f',
    authDomain: 'modul-12-e205f.firebaseapp.com',
    storageBucket: 'modul-12-e205f.firebasestorage.app',
  );
}
